# Generated by Django 3.0.1 on 2019-12-20 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waking_soundly_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MainSongModel',
            new_name='MainSong',
        ),
        migrations.RenameModel(
            old_name='TransitionModel',
            new_name='Transition',
        ),
        migrations.RenameModel(
            old_name='UserSongModel',
            new_name='UserSong',
        ),
    ]
