# Generated by Django 3.0.1 on 2019-12-23 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waking_soundly_app', '0004_usersong_byuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersong',
            name='byUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userSongs', to=settings.AUTH_USER_MODEL),
        ),
    ]
