export const GET_USERMUSIC = 'GET_USERMUSIC';
export const DELETE_USERMUSIC = 'DELETE_USERMUSIC';
export const ADD_USERMUSIC = 'ADD_USERMUSIC';
export const EDIT_USERMUSIC = 'EDIT_USERMUSIC';

export const GET_MAINMUSIC = 'GET_MAINMUSIC';

export const GET_TRANSITIONS = 'GET_TRANSITIONS';

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";